"""Grok media gallery endpoints.

  GET /api/gallery  paginated list of every Grok job that produced media
                    output, with filters by user/profile/job_type/date.
                    Super_admin sees all rows; admin → own domain; user → own.
"""
from __future__ import annotations

import re
import uuid
from datetime import datetime
from typing import Literal

from fastapi import APIRouter, Query
from pydantic import BaseModel
from sqlalchemy import func, select

from app.core.deps import CurrentUser, DbSession
from app.models import Domain, FlowJob, Job, Profile, User
# Gateway models dropped from plxeditor-studio
from app.modules.grok.files.router import make_share_token

router = APIRouter(prefix="/api/gallery", tags=["gallery"])


# Match `/api/files/<uuid>/download` inside Job.result_url so we can attach
# a short-lived `?token=` for inline rendering by <img>/<video> tags.
_FILE_URL_RE = re.compile(r"^/api/files/([0-9a-f-]{36})/download$")


class GalleryItem(BaseModel):
    job_id: uuid.UUID
    job_type: str
    provider: str
    prompt: str
    result_url: str
    profile_name: str | None
    user_email: str | None
    # Domain (tenant) info so super_admin can group/filter by client.
    domain_id: uuid.UUID | None = None
    domain_hostname: str | None = None
    domain_brand_name: str | None = None
    created_at: datetime
    completed_at: datetime | None
    file_size: int | None


class GalleryPage(BaseModel):
    items: list[GalleryItem]
    total: int
    offset: int
    limit: int


@router.get("", response_model=GalleryPage)
async def list_gallery(
    user: CurrentUser, db: DbSession,
    job_type: Literal["image", "video", ""] = Query(default=""),
    user_id: uuid.UUID | None = Query(default=None),
    profile_id: uuid.UUID | None = Query(default=None),
    domain_id: uuid.UUID | None = Query(default=None,
        description="super_admin only — filter by tenant domain"),
    q: str | None = Query(default=None,
        description="Substring search on the prompt text"),
    date_from: datetime | None = Query(default=None),
    date_to: datetime | None = Query(default=None),
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=30, ge=1, le=100),
) -> GalleryPage:
    """Scope:
      super_admin → all media in the platform (can filter by domain_id)
      admin       → media generated by users in their domain
      user        → their own media only
    """
    base = (
        select(Job, Profile, User, Domain)
        .outerjoin(Profile, Profile.id == Job.profile_id)
        .outerjoin(User, User.id == Job.user_id)
        .outerjoin(Domain, Domain.id == User.domain_id)
        .where(Job.status == "success", Job.result_url.is_not(None))
    )

    if user.role == "user" or user.role == "support":
        base = base.where(Job.user_id == user.id)
    elif user.role == "admin":
        base = base.where(User.domain_id == user.domain_id)
    elif user.role == "super_admin" and domain_id is not None:
        base = base.where(User.domain_id == domain_id)

    if job_type:
        base = base.where(Job.job_type == job_type)
    if user_id:
        base = base.where(Job.user_id == user_id)
    if profile_id:
        base = base.where(Job.profile_id == profile_id)
    if q:
        # Case-insensitive substring search — sufficient for prompts UI
        # without needing a full-text index.
        base = base.where(Job.prompt.ilike(f"%{q.strip()}%"))
    if date_from:
        base = base.where(Job.created_at >= date_from)
    if date_to:
        base = base.where(Job.created_at <= date_to)

    # Cheap count without ordering / pagination — same WHERE.
    total = (await db.execute(
        select(func.count()).select_from(base.subquery())
    )).scalar_one() or 0

    rows = (await db.execute(
        base.order_by(Job.completed_at.desc().nullslast(), Job.created_at.desc())
        .offset(offset).limit(limit)
    )).all()

    items = []
    for j, p, u, d in rows:
        raw = j.result_url or ""
        m = _FILE_URL_RE.match(raw)
        if m:
            try:
                token = make_share_token(uuid.UUID(m.group(1)))
                raw = f"{raw}?token={token}"
            except Exception:  # noqa: BLE001 — never block listing on signing errors
                pass
        items.append(GalleryItem(
            job_id=j.id,
            job_type=j.job_type,
            provider=j.provider,
            prompt=j.prompt or "",
            result_url=raw,
            profile_name=p.name if p else None,
            user_email=u.email if u else None,
            domain_id=d.id if d else None,
            domain_hostname=d.hostname if d else None,
            domain_brand_name=d.brand_name if d else None,
            created_at=j.created_at,
            completed_at=j.completed_at,
            file_size=None,
        ))
    return GalleryPage(items=items, total=int(total), offset=offset, limit=limit)


# ─── Flow gallery ──────────────────────────────────────────────────────────
#
# Each row = 1 completed FlowJob. Operation buckets:
#   video output  → cut / merge / add-audio / speed / resize / crop
#   audio output  → extract-audio
#   frame output  → extract-frames (zip of stills)
# `output_kind` collapses the operation to a bucket so the FE can render
# 3 sub-tabs without duplicating the mapping table.

_FLOW_OP_KIND = {
    "cut":            "video",
    "merge":          "video",
    "add-audio":      "video",
    "speed":          "video",
    "resize":         "video",
    "crop":           "video",
    "extract-audio":  "audio",
    "extract-frames": "frame",
}


class FlowGalleryItem(BaseModel):
    job_id: uuid.UUID
    operation: str
    output_kind: str
    output_url: str | None
    output_filename: str | None
    file_size: int | None
    duration: float | None
    user_email: str | None
    domain_id: uuid.UUID | None = None
    domain_hostname: str | None = None
    domain_brand_name: str | None = None
    created_at: datetime
    completed_at: datetime | None


class FlowGalleryPage(BaseModel):
    items: list[FlowGalleryItem]
    total: int
    offset: int
    limit: int


@router.get("/flow", response_model=FlowGalleryPage)
async def list_flow_gallery(
    user: CurrentUser, db: DbSession,
    output_kind: Literal["video", "audio", "frame", ""] = Query(default=""),
    operation: str | None = Query(default=None),
    user_id: uuid.UUID | None = Query(default=None),
    domain_id: uuid.UUID | None = Query(default=None),
    date_from: datetime | None = Query(default=None),
    date_to: datetime | None = Query(default=None),
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=30, ge=1, le=100),
) -> FlowGalleryPage:
    base = (
        select(FlowJob, User, Domain)
        .outerjoin(User, User.id == FlowJob.user_id)
        .outerjoin(Domain, Domain.id == User.domain_id)
        .where(FlowJob.status == "completed", FlowJob.output_url.is_not(None))
    )
    if user.role in ("user", "support"):
        base = base.where(FlowJob.user_id == user.id)
    elif user.role == "admin":
        base = base.where(User.domain_id == user.domain_id)
    elif user.role == "super_admin" and domain_id is not None:
        base = base.where(User.domain_id == domain_id)
    if output_kind:
        ops = [op for op, kind in _FLOW_OP_KIND.items() if kind == output_kind]
        if ops:
            base = base.where(FlowJob.operation.in_(ops))
    if operation:
        base = base.where(FlowJob.operation == operation)
    if user_id:
        base = base.where(FlowJob.user_id == user_id)
    if date_from:
        base = base.where(FlowJob.created_at >= date_from)
    if date_to:
        base = base.where(FlowJob.created_at <= date_to)
    total = (await db.execute(
        select(func.count()).select_from(base.subquery())
    )).scalar_one() or 0
    rows = (await db.execute(
        base.order_by(FlowJob.completed_at.desc().nullslast(), FlowJob.created_at.desc())
        .offset(offset).limit(limit)
    )).all()
    items: list[FlowGalleryItem] = []
    for fj, u, d in rows:
        items.append(FlowGalleryItem(
            job_id=fj.id,
            operation=fj.operation,
            output_kind=_FLOW_OP_KIND.get(fj.operation, "video"),
            output_url=fj.output_url,
            output_filename=fj.output_filename,
            file_size=fj.file_size,
            duration=float(fj.duration) if fj.duration is not None else None,
            user_email=u.email if u else None,
            domain_id=d.id if d else None,
            domain_hostname=d.hostname if d else None,
            domain_brand_name=d.brand_name if d else None,
            created_at=fj.created_at,
            completed_at=fj.completed_at,
        ))
    return FlowGalleryPage(items=items, total=int(total), offset=offset, limit=limit)


# ─── Gateway gallery ───────────────────────────────────────────────────────
#
# Each row = 1 successful GwRequest. We compute a short response excerpt
# (~200 chars) by walking common vendor response shapes so the FE has
# something to show without forcing it to know about each vendor's JSON.


class GatewayGalleryItem(BaseModel):
    gw_id: str
    vendor_code: str | None
    vendor_name: str | None
    function_code: str | None
    model: str | None
    response_excerpt: str | None
    latency_ms: int | None
    tokens_input: int | None
    tokens_output: int | None
    cost_cents: int | None
    domain_id: uuid.UUID | None = None
    domain_hostname: str | None = None
    domain_brand_name: str | None = None
    created_at: datetime


class GatewayGalleryPage(BaseModel):
    items: list[GatewayGalleryItem]
    total: int
    offset: int
    limit: int


def _extract_gw_excerpt(body: dict | None) -> str | None:
    if not isinstance(body, dict):
        return None
    paths = (
        ("choices", 0, "message", "content"),
        ("content", 0, "text"),
        ("candidates", 0, "content", "parts", 0, "text"),
        ("text",),
        ("output",),
    )
    for path in paths:
        try:
            cur = body
            for k in path:
                cur = cur[k]
            if isinstance(cur, str) and cur.strip():
                return cur[:200]
        except (KeyError, IndexError, TypeError):
            continue
    return None


@router.get("/gateway", response_model=GatewayGalleryPage)
async def list_gateway_gallery(
    user: CurrentUser, db: DbSession,
    vendor_code: str | None = Query(default=None),
    function_code: str | None = Query(default=None),
    domain_id: uuid.UUID | None = Query(default=None),
    date_from: datetime | None = Query(default=None),
    date_to: datetime | None = Query(default=None),
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=30, ge=1, le=100),
) -> GatewayGalleryPage:
    return GatewayGalleryPage(items=[], total=0, offset=offset, limit=limit)
