"""Auto-sync nginx vhost configs from Domain rows.

Backend writes `.conf` files into a directory the host nginx includes. A
host-side reloader (cron / systemd path unit) picks up changes and runs
`nginx -s reload`. This avoids needing root/SSH from the container.

Config dir is configurable via `NGINX_VHOSTS_DIR` env. Defaults to
`/host_nginx_vhosts` which the docker-compose mounts from the host's
`/etc/nginx/grokflow-vhosts/` (created by deploy/setup-host-nginx.sh).

Files are named `grokflow-<sanitized-hostname>.conf` so they don't collide
with admin's other configs. Wildcard '*' is the default fallback row in DB
and intentionally has no vhost file (the host's existing default_server
or non-matching catch-all handles it).
"""
from __future__ import annotations

import os
import re
from pathlib import Path

# Where to write vhost files. Host mounts /etc/nginx/grokflow-vhosts/ here.
VHOSTS_DIR = Path(os.environ.get("NGINX_VHOSTS_DIR", "/host_nginx_vhosts"))

# Where to send proxy_pass — must be the host port that maps to the
# grokflow-frontend container (currently 127.0.0.1:5173 on host).
FRONTEND_UPSTREAM = os.environ.get("NGINX_FRONTEND_UPSTREAM", "http://127.0.0.1:5173")
# Backend (FastAPI) upstream — must serve /api/* and /openapi.json.
BACKEND_UPSTREAM = os.environ.get("NGINX_BACKEND_UPSTREAM", "http://127.0.0.1:8000")

# Safe-hostname regex. Anything outside this set is rejected (the admin UI
# should already validate, but defense in depth).
_HOSTNAME_RE = re.compile(r"^[a-z0-9]([a-z0-9\-\.]{0,253}[a-z0-9])?$")


def _is_writable() -> bool:
    """True when the mounted dir exists and is writable.

    Returns False on dev machines / tests where the dir isn't mounted —
    callers should treat this as "skip silently" to keep tests passing
    without host nginx infrastructure.
    """
    try:
        return VHOSTS_DIR.exists() and os.access(VHOSTS_DIR, os.W_OK)
    except OSError:
        return False


def _safe_hostname(hostname: str) -> str | None:
    """Sanitize + validate. Returns None if hostname is unsafe."""
    h = hostname.strip().lower()
    if h == "*" or not h:
        return None
    if not _HOSTNAME_RE.match(h):
        return None
    return h


def _config_path(hostname: str) -> Path:
    safe = hostname.replace(".", "_")
    return VHOSTS_DIR / f"grokflow-{safe}.conf"


def _render_vhost(hostname: str) -> str:
    return f"""# Auto-generated by GrokFlow admin — do not edit by hand.
# Domain row: {hostname}
server {{
    listen 80;
    server_name {hostname};

    client_max_body_size 25m;

    # API + docs go to FastAPI. Listed first so they win the longest-prefix
    # match over the catch-all `/` location below.
    location ~ ^/(api|openapi.json|docs|redoc|f)(/|$) {{
        proxy_pass {BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }}

    # /vnc/<short>/... → kasmweb container on docker bridge.
    # $vnc_upstream is set by the map in _vnc_map.conf (same dir as this file).
    # Backend refreshes that map whenever a VNC container spawns / dies.
    location ~ ^/vnc/([a-f0-9]+)/(.*)$ {{
        set $vnc_short $1;
        set $vnc_rest  $2;
        if ($vnc_upstream = "_none_") {{
            return 502 "VNC container not registered yet — retry Auto login.";
        }}
        proxy_pass http://$vnc_upstream:6901/$vnc_rest$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # WebSocket upgrade for websockify
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering off;
    }}

    location / {{
        proxy_pass {FRONTEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }}
}}
"""


# ─── VNC map (short_id → container IP) ─────────────────────────────────────
#
# Each kasmweb VNC container we spawn is named `grokflow-vnc-<short_id>` where
# <short_id> is the first 12 hex of the profile's UUID. The vhost /vnc/<short>/
# location proxies to the container's bridge IP via the nginx `map` defined
# in `_vnc_map.conf` (file + nginx variable name configurable so prod and
# staging stacks on the same host don't share map state).
#
# Per-env env vars (compose passes these in via .env.<env>):
#   VNC_NETWORK   docker network to spawn VNC on  (default: grokflow_default)
#   VNC_MAP_FILE  filename inside VHOSTS_DIR      (default: _vnc_map.conf)
#   VNC_MAP_VAR   nginx variable name            (default: vnc_upstream)
#
# Called by:
#   - profiles router on start-vnc-session / finish-vnc-session / stop-vnc
#   - app startup (best-effort sync after a fresh container)
_VNC_NETWORK = os.environ.get("VNC_NETWORK", "grokflow_default")
_VNC_MAP_FILE = os.environ.get("VNC_MAP_FILE", "_vnc_map.conf")
_VNC_MAP_VAR = os.environ.get("VNC_MAP_VAR", "vnc_upstream")
VNC_MAP_PATH = VHOSTS_DIR / _VNC_MAP_FILE


def _collect_vnc_entries() -> list[tuple[str, str]]:
    """One pass over running VNC containers on THIS env's network.

    Returns [(short_id, ip), ...]. Skips containers whose Network metadata
    is still empty (Docker can return the container in `list()` a heartbeat
    before NetworkSettings is fully populated, especially right after
    `docker run`). Containers attached to a different docker network than
    `VNC_NETWORK` are ignored so prod and staging stacks don't see each
    other's VNCs (each env writes its own map file).
    """
    import docker
    client = docker.from_env()
    entries: list[tuple[str, str]] = []
    for c in client.containers.list(filters={"name": "grokflow-vnc-"}):
        if not c.name.startswith("grokflow-vnc-"):
            continue
        short = c.name[len("grokflow-vnc-"):]
        nets = c.attrs.get("NetworkSettings", {}).get("Networks") or {}
        # Strictly require the env's network — keeps prod and staging maps
        # isolated. If a container is on the wrong network it's leftover
        # from a previous config and not addressable via this env's vhost.
        if _VNC_NETWORK not in nets:
            continue
        ip = nets[_VNC_NETWORK].get("IPAddress") or ""
        if short and ip:
            entries.append((short, ip))
    return entries


def refresh_vnc_map_until_present(short_id: str, *, timeout_sec: float = 10.0,
                                  interval_sec: float = 0.5) -> bool:
    """Refresh the nginx VNC map and **wait** until `short_id` appears in
    the collected entries (or timeout). Use this from request handlers
    that have just spawned a VNC container — guarantees the user's iframe
    won't 502 because the map is one tick behind Docker IPAM.

    Returns True when the entry is present, False if the timeout expires
    (caller can log a warning but should still let the user retry — the
    background idle_cleanup loop will pick it up shortly anyway).
    """
    import time
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        refresh_vnc_map()
        entries = dict(_collect_vnc_entries())
        if short_id in entries:
            return True
        time.sleep(interval_sec)
    # Last-attempt refresh in case the container settled right at the deadline.
    refresh_vnc_map()
    return short_id in dict(_collect_vnc_entries())


def refresh_vnc_map() -> bool:
    """Rebuild _vnc_map.conf from currently running VNC containers.

    Idempotent. Returns True on write, False on skip (no docker SDK, dir not
    writable, or no docker.sock). Never raises — callers should treat the
    map as best-effort; existing entries keep working until next refresh.

    Race-tolerant: callers (e.g. profiles router after start-vnc-session)
    invoke this immediately after `docker run`, but Docker daemon may
    return the container in `list()` a heartbeat before NetworkSettings
    is populated — `_collect_vnc_entries` then returns no IP for that
    container and nginx sees `_none_`. Retry a few times with short
    sleeps until either every running container has an IP, or we
    exhaust the budget (then write what we have — the systemd path
    watcher will fire on next call anyway).

    Emits `[vnc-map]` log lines so operators can grep `docker logs
    grokflow-backend-1 | grep vnc-map` and see actual write/no-op/skip
    state — without this we silently no-op'd for 2h once (May 2026
    incident) because the idle-cleanup container was missing the
    vhost-dir mount.
    """
    if not _is_writable():
        print(f"[vnc-map] skip: {VNC_MAP_PATH.parent} not writable (mount missing?)", flush=True)
        return False
    try:
        import docker  # imported lazily so unit tests don't need it
        docker.from_env()
    except Exception as exc:
        print(f"[vnc-map] skip: docker SDK unavailable ({type(exc).__name__})", flush=True)
        return False

    import time
    entries: list[tuple[str, str]] = []
    expected_count = -1
    # Wider budget (5s) — Docker IPAM can take a few seconds to attach
    # network metadata when multiple containers spawn back-to-back, and
    # the `entries == expected_count` break-condition needs to wait that
    # long or we write an incomplete map (then nginx serves stale entries
    # until the next refresh).
    for attempt in range(20):  # 20 × 250ms = 5s total budget
        try:
            import docker as _d
            client = _d.from_env()
            running = client.containers.list(filters={"name": "grokflow-vnc-"})
            # Only count containers attached to THIS env's network — without
            # this filter the count includes the other env's VNCs and never
            # matches our entries list, so the loop wastes its whole budget
            # and may write an empty map if our containers' IP isn't ready
            # yet.
            expected_count = 0
            for c in running:
                if not c.name.startswith("grokflow-vnc-"):
                    continue
                nets = (c.attrs.get("NetworkSettings", {}) or {}).get("Networks") or {}
                if _VNC_NETWORK in nets:
                    expected_count += 1
            entries = _collect_vnc_entries()
        except Exception:
            entries = []
            expected_count = -1
        if expected_count >= 0 and len(entries) == expected_count:
            break  # every container has its IP
        time.sleep(0.25)

    lines: list[str] = [
        "# Auto-generated by GrokFlow backend — do not edit by hand.",
        "# Maps VNC short_id (first 12 hex of profile UUID) -> container IP.",
        "# Refreshed whenever a VNC container is spawned or torn down.",
        f"map $vnc_short ${_VNC_MAP_VAR} {{",
    ]
    for short, ip in entries:
        lines.append(f"    {short} {ip};")
    lines.append('    default "_none_";')
    lines.append("}")
    text = "\n".join(lines) + "\n"

    try:
        # Only write if content actually changed — avoids spurious systemd
        # path-watcher reloads (each call writes ~1s of nginx reload work).
        try:
            existing = VNC_MAP_PATH.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        if existing == text:
            return True  # no-op success (silent — happens 4×/min from the loop)

        # Atomic write via temp-file + rename. The vhost dir is bind-mounted
        # from the host's /etc/nginx/grokflow-vhosts/ where the placeholder
        # file is owned by root (created by install_nginx_watcher.sh under
        # sudo). The backend gunicorn worker runs as uid 10001, so it can't
        # `open(path, "w")` a root-owned file even though it CAN write into
        # the dir (drwxrwsr-x with the setgid bit makes gid grokflow). Atomic
        # rename only needs dir-write, and the resulting file becomes uid
        # 10001:10001 — subsequent writes go direct-path. Without this fix
        # we silently EACCES'd for hours on new VNC profiles.
        import os
        tmp_path = VNC_MAP_PATH.with_suffix(VNC_MAP_PATH.suffix + ".tmp")
        tmp_path.write_text(text, encoding="utf-8")
        os.replace(tmp_path, VNC_MAP_PATH)
        short_ids = [s for s, _ in entries]
        print(
            f"[vnc-map] wrote {len(entries)} entr"
            f"{'y' if len(entries) == 1 else 'ies'}: {short_ids}",
            flush=True,
        )
        return True
    except OSError as exc:
        print(f"[vnc-map] write failed: {exc}", flush=True)
        return False


def write_vhost(hostname: str) -> bool:
    """Idempotently write the nginx vhost file for a domain.

    Returns True on success, False on skip (unsafe hostname, dir not mounted,
    or write error). Callers should NOT raise — domain CRUD must succeed even
    if nginx sync is broken.
    """
    if not _is_writable():
        return False
    h = _safe_hostname(hostname)
    if not h:
        return False
    path = _config_path(h)
    try:
        path.write_text(_render_vhost(h), encoding="utf-8")
        return True
    except OSError:
        return False


def delete_vhost(hostname: str) -> bool:
    """Remove the nginx vhost file for a domain. Idempotent."""
    if not _is_writable():
        return False
    h = _safe_hostname(hostname)
    if not h:
        return False
    path = _config_path(h)
    try:
        path.unlink(missing_ok=True)
        return True
    except OSError:
        return False
