#!/usr/bin/env bash
# customer_setup.sh — first-time install for a flowgrok-family product.
#
# Usage on the customer's VPS (Linux or WSL2 Ubuntu):
#   curl -fsSL https://raw.githubusercontent.com/nt7310063-boop/<product>/main/_scripts/customer_setup.sh | bash
# OR if already cloned:
#   cd <product> && bash _scripts/customer_setup.sh
#
# What it does:
#   1. Sanity-check the host (docker, git, RAM, disk)
#   2. Generate secrets + write .env (refuse to overwrite an existing one)
#   3. Build the stack
#   4. Run alembic migrations
#   5. Prompt for admin email/password + create the first admin user
#   6. Print the URLs to log in
#
# Idempotency: safe to re-run AFTER a clean-up — `docker compose down -v`
# wipes data, then this script bootstraps fresh.

set -euo pipefail

# ---------------------------- helpers ----------------------------
red()    { printf '\033[1;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[1;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[1;33m%s\033[0m\n' "$*"; }
cyan()   { printf '\033[1;36m%s\033[0m\n' "$*"; }
die()    { red "ERROR: $*"; exit 1; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "$1 not installed. Run:  sudo apt install -y $1"
}

# ---------------------------- sanity ----------------------------
cyan "==> Host sanity"
require_cmd docker
require_cmd git
require_cmd openssl
require_cmd curl
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing"

ram_mb=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 0)
disk_gb=$(df -BG --output=avail / 2>/dev/null | tail -1 | tr -d ' G' || echo 0)
[[ ${ram_mb:-0} -ge 3500 ]] || yellow "WARNING: < 4GB RAM (have ${ram_mb}MB). Chromium VNC may OOM."
[[ ${disk_gb:-0} -ge 30 ]]  || yellow "WARNING: < 30GB free disk (have ${disk_gb}GB). Image pulls + Chromium profiles need room."

cd "$(dirname "$0")/.."
PROJECT_ROOT="$(pwd)"
green "Project root: $PROJECT_ROOT"

# ---------------------------- .env ----------------------------
if [[ -f .env ]]; then
    yellow "==> .env already exists — leaving untouched"
else
    cyan "==> Generating .env with random secrets"
    read -rp "Public domain (e.g. editor.example.com or your-vps-ip): " PUB_DOMAIN
    [[ -n "$PUB_DOMAIN" ]] || die "Public domain required"

    # Detect whether user gave a domain (use https) or an IP (use http)
    if [[ "$PUB_DOMAIN" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        SCHEME="http"
    else
        SCHEME="https"
    fi

    read -rp "Backend host port [8000]: " BE_PORT; BE_PORT="${BE_PORT:-8000}"
    read -rp "Frontend host port [5173]: " FE_PORT; FE_PORT="${FE_PORT:-5173}"

    cat > .env <<EOF
# Generated by customer_setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || docker run --rm python:3.11-slim sh -c "pip install -q cryptography && python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'")
PUBLIC_DOMAIN=${PUB_DOMAIN}
PUBLIC_API_URL=${SCHEME}://${PUB_DOMAIN}$([[ "$BE_PORT" != "80" && "$BE_PORT" != "443" ]] && echo ":${BE_PORT}")
POSTGRES_USER=flowgrok
POSTGRES_DB=flowgrok
GUNICORN_WORKERS=2
BACKEND_HOST_PORT=${BE_PORT}
FRONTEND_HOST_PORT=${FE_PORT}
EOF
    chmod 600 .env
    green ".env written"
fi

# ---------------------------- build + up ----------------------------
cyan "==> docker compose up -d --build (5–15 min first time — Chromium image pull)"
docker compose up -d --build

cyan "==> Waiting for postgres + redis healthy"
sleep 15

# ---------------------------- migrate ----------------------------
cyan "==> Alembic migrate"
docker compose run --rm --entrypoint "" backend alembic upgrade head

cyan "==> Restart backend so seed_default_plans runs against fresh schema"
docker compose restart backend
sleep 10

# ---------------------------- admin user ----------------------------
if docker compose exec -T backend python -c "
import asyncio, sys
from sqlalchemy import select
from app.core.database import SessionLocal
from app.models import User
async def main():
    async with SessionLocal() as db:
        r = await db.execute(select(User).limit(1))
        sys.exit(0 if r.scalar_one_or_none() else 1)
asyncio.run(main())
" 2>/dev/null; then
    yellow "==> Admin user already exists — skipping create"
else
    cyan "==> Create first admin user"
    read -rp "Admin email: " ADMIN_EMAIL
    [[ -n "$ADMIN_EMAIL" ]] || die "Email required"
    read -rsp "Admin password (min 8 chars): " ADMIN_PASS; echo
    [[ ${#ADMIN_PASS} -ge 8 ]] || die "Password too short"

    docker compose exec -T backend python -m app.scripts.create_admin \
        --email "$ADMIN_EMAIL" \
        --password "$ADMIN_PASS" \
        --role super_admin

    # zero out so it doesn't linger in history / env
    ADMIN_PASS=""
fi

# ---------------------------- smoke ----------------------------
cyan "==> Smoke test"
BE_PORT=$(grep '^BACKEND_HOST_PORT=' .env | cut -d= -f2)
FE_PORT=$(grep '^FRONTEND_HOST_PORT=' .env | cut -d= -f2)

if curl -fsS "http://localhost:${BE_PORT}/health" >/dev/null; then
    green "Backend healthy on :${BE_PORT}"
else
    red "Backend not responding — check: docker compose logs backend --tail=50"
fi

if curl -fsS "http://localhost:${FE_PORT}/" -o /dev/null; then
    green "Frontend healthy on :${FE_PORT}"
else
    red "Frontend not responding — check: docker compose logs frontend --tail=20"
fi

# ---------------------------- done ----------------------------
echo
green "================================================================"
green " Install complete"
green "================================================================"
echo
echo "  Frontend: $(grep '^PUBLIC_API_URL=' .env | cut -d= -f2- | sed 's|:[0-9]*$||')"
echo "  Direct FE: http://$(grep '^PUBLIC_DOMAIN=' .env | cut -d= -f2):${FE_PORT}/"
echo "  Backend:   http://$(grep '^PUBLIC_DOMAIN=' .env | cut -d= -f2):${BE_PORT}/health"
echo
echo "  Login with the admin credentials you just entered."
echo
echo "  Next steps:"
echo "    - To put a real domain + TLS in front: sudo bash deploy/install_nginx.sh <domain> <email>"
echo "    - To watch logs:    docker compose logs -f"
echo "    - To stop:          docker compose stop"
echo "    - To restart:       docker compose restart"
echo "    - To update:        bash _scripts/customer_update.sh"
echo "    - To uninstall:     docker compose down -v       # !!! wipes data"
echo
