"""Server health-check telemetry: metrics history + alerts

Revision ID: 0039
Revises: 0038

Two tables to back the Zabbix-style dashboard:

  • server_metrics_history — one row per (server, sample). Background
    worker SSH-probes every active server every ~60s and appends a row.
    Counters: cpu_pct, ram_used / ram_total, disk_used / disk_total,
    load_avg_1m, uptime_seconds. Old rows auto-pruned to keep ~7 days.

  • server_alerts — open / resolved problem rows the dashboard widget
    counts by severity (disaster / high / average / warning / info).
    Generated by the monitor worker when a threshold trips
    (RAM > 90 %, disk > 85 %, server unreachable, ...). Once recovered,
    the worker fills resolved_at — kept in DB for the alert history.

The Server row also gets `monitor_enabled` (default true) so admin can
suspend probing per-server (e.g. a maintenance window) without deleting
the row.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "servers",
        sa.Column(
            "monitor_enabled", sa.Boolean(),
            nullable=False, server_default="true",
        ),
    )

    op.create_table(
        "server_metrics_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, primary_key=True),
        sa.Column(
            "server_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("servers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),  # active|unreachable|stopped
        sa.Column("cpu_pct", sa.Float(), nullable=True),
        sa.Column("ram_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("ram_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("disk_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("disk_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("load_avg_1m", sa.Float(), nullable=True),
        sa.Column("uptime_seconds", sa.BigInteger(), nullable=True),
        # SSH probe duration. If the box is slow this stays high even when
        # nothing is wrong CPU-wise — useful signal on its own.
        sa.Column("probe_duration_ms", sa.Integer(), nullable=True),
        # Optional error message when the probe failed entirely.
        sa.Column("error_message", sa.Text(), nullable=True),
    )
    op.create_index(
        "ix_server_metrics_server_time",
        "server_metrics_history",
        ["server_id", "sampled_at"],
    )

    op.create_table(
        "server_alerts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "server_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("servers.id", ondelete="CASCADE"),
            nullable=False, index=True,
        ),
        # Logical signal that triggered: "ssh_unreachable", "ram_critical",
        # "disk_critical", "load_high", "uptime_high" (reboot needed)...
        sa.Column("kind", sa.String(50), nullable=False),
        # disaster | high | average | warning | information (Zabbix levels).
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        # Snapshot of the trigger value at the moment of opening, e.g. "92.3".
        sa.Column("trigger_value", sa.String(50), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(timezone=True),
            server_default=sa.func.now(), nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "acknowledged_by", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
    )
    op.create_index(
        "ix_server_alerts_server_severity",
        "server_alerts", ["server_id", "severity", "resolved_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_server_alerts_server_severity", table_name="server_alerts")
    op.drop_table("server_alerts")
    op.drop_index("ix_server_metrics_server_time", table_name="server_metrics_history")
    op.drop_table("server_metrics_history")
    op.drop_column("servers", "monitor_enabled")
