import uuid

from fastapi import APIRouter, Header, Query
from fastapi.responses import Response
from jose import JWTError, jwt
from sqlalchemy import select

from app.core.config import settings
from app.core.deps import DbSession
from app.core.exceptions import NotFound, PermissionDenied
from app.core.security import create_short_token, hash_api_key
from app.models import ApiKey, File, User

from . import service

router = APIRouter(prefix="/api/files", tags=["files"])

# Short alias router — `/f/<id>` instead of `/api/files/<id>/download`.
# Same handler under the hood (download_file), just registered under a
# different prefix so partners get a memorable, embeddable URL.
short_router = APIRouter(prefix="/f", tags=["files"])

# Singular-prefix alias — `/api/file/<id>`. Some partners prefer this
# RESTful-ish shape over the `/f/` short link. Same handler.
api_file_router = APIRouter(prefix="/api/file", tags=["files"])


# Admin family: tenant admins and super_admin can read everyone's files
# in their scope. The legacy check rejected super_admin (role != "admin")
# which also silently broke the gallery on /api/files/.../download.
_ADMIN_ROLES = {"admin", "super_admin"}


def _can_read(user: User, file_owner_id: uuid.UUID) -> bool:
    return user.id == file_owner_id or user.role in _ADMIN_ROLES


async def _resolve_bearer(db, bearer: str) -> User | None:
    """Resolve a Bearer token to a User.

    Accepts BOTH a GrokFlow session JWT (sub=<user_id>) AND a partner
    API key (`uxpm_live_*`, sha256-hashed in api_keys table). Partners
    using the /api/client/* contract get `image_urls: [/api/files/<id>/download]`
    back; without API-key acceptance here they couldn't actually
    download the results their own contract told them about. Now they
    can pass the same Bearer header for both submit and download.
    """
    bearer = bearer.strip()
    if not bearer:
        return None
    # Try JWT first — cheaper than a DB hit when the token is a session.
    try:
        payload = jwt.decode(bearer, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])
        sub = payload.get("sub")
        if sub:
            try:
                u = await db.get(User, uuid.UUID(sub))
                if u and u.status == "active":
                    return u
            except ValueError:
                pass
    except JWTError:
        pass
    # Fall back to API key: sha256 the raw string and look it up.
    key_hash = hash_api_key(bearer)
    api_key = (await db.execute(
        select(ApiKey).where(ApiKey.key_hash == key_hash)
    )).scalar_one_or_none()
    if not api_key or api_key.status != "active":
        return None
    u = await db.get(User, api_key.user_id)
    if not u or u.status != "active":
        return None
    return u


@router.get("/{file_id}/meta")
async def get_file_meta(
    file_id: uuid.UUID,
    db: DbSession,
    authorization: str | None = Header(default=None),
) -> dict:
    """File metadata (JSON). Moved from `/api/files/{file_id}` to
    `/api/files/{file_id}/meta` — the bare-id GET now serves the file
    content directly so partners can paste the URL anywhere.

    Auth via Bearer — accepts both GrokFlow JWT and partner API key
    (uxpm_live_*), same as /download.
    """
    f = await db.get(File, file_id)
    if not f:
        raise NotFound("file")
    if not authorization or not authorization.lower().startswith("bearer "):
        raise PermissionDenied()
    bearer = authorization.split(" ", 1)[1]
    user = await _resolve_bearer(db, bearer)
    if not user or not _can_read(user, f.user_id):
        raise PermissionDenied()
    return {
        "id": str(f.id),
        "file_name": f.file_name,
        "file_type": f.file_type,
        "mime_type": f.mime_type,
        "file_size": f.file_size,
        "download_url": f"/api/files/{f.id}",
    }


def make_share_token(file_id: uuid.UUID, minutes: int = 60 * 24) -> str:
    """Short-lived JWT that authorises a single file download.

    Embedded as `?token=...` on inline media URLs (gallery cells, preview
    modal). Lets <img>/<video> tags hit /download without sending an
    Authorization header.
    """
    return create_short_token(
        subject=f"file:{file_id}",
        extra={"file_id": str(file_id), "scope": "file_download"},
        minutes=minutes,
    )


def _validate_share_token(token: str, file_id: uuid.UUID) -> bool:
    try:
        payload = jwt.decode(token, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])
    except JWTError:
        return False
    return payload.get("file_id") == str(file_id) and payload.get("scope") == "file_download"


# File types that are partner-facing outputs (generated by Grok jobs).
# These are served as public bare URLs — same model as Replicate / OpenAI
# image responses where `file_id` (an unguessable UUIDv4) IS the secret.
# Adding ?token= still works and adds nothing on top.
_PUBLIC_FILE_TYPES = {"image", "video"}


@router.get("/{file_id}/download")
@router.head("/{file_id}/download")
@router.get("/{file_id}")
@router.head("/{file_id}")
@short_router.get("/{file_id}")
@short_router.head("/{file_id}")
@api_file_router.get("/{file_id}")
@api_file_router.head("/{file_id}")
async def download_file(
    file_id: uuid.UUID,
    db: DbSession,
    token: str | None = Query(default=None),
    authorization: str | None = Header(default=None),
) -> Response:
    """Public-ish download. Auth strategy depends on file_type:

    Public types (`image`, `video` — generated outputs): bare URL works,
    no token, no Authorization needed. Same pattern as Replicate /
    OpenAI image responses. file_id is a 122-bit UUID, so the URL itself
    is the secret — unguessable without prior issuance. Lets partners
    embed `<img src=...>` in HTML, share to messaging apps, paste in a
    browser address bar, etc., without dealing with token rotation.

    Private types (`input` uploaded references, `installer`, anything
    else): still require either `?token=<share-token>` or `Authorization:
    Bearer <jwt-or-api-key>`. Partners can't read each other's input
    files even if they guess the id.

    HEAD requests are accepted so link-unfurl bots (Slack/Discord/Telegram
    preview, iOS Quick Look, CDN cache validation) get a useful response
    instead of 405.
    """
    f = await db.get(File, file_id)
    if not f:
        raise NotFound("file")

    is_public = f.file_type in _PUBLIC_FILE_TYPES

    if not is_public:
        # Private file → need explicit credential.
        authorized = False
        if token and _validate_share_token(token, file_id):
            authorized = True
        elif authorization and authorization.lower().startswith("bearer "):
            bearer = authorization.split(" ", 1)[1]
            u = await _resolve_bearer(db, bearer)
            if u and _can_read(u, f.user_id):
                authorized = True
        if not authorized:
            raise PermissionDenied()

    data = await service.read_file_bytes(f)
    return Response(
        content=data,
        media_type=f.mime_type or "application/octet-stream",
        headers={
            "Content-Disposition": f'inline; filename="{f.file_name}"',
            # Public outputs get long-cache (a generated image never
            # changes). Private files keep short cache + private scope.
            "Cache-Control": (
                "public, max-age=31536000, immutable"
                if is_public
                else "private, max-age=86400"
            ),
        },
    )


# Glue both prefixes together so the module's single manifest entry
# can register the meta+download routes (/api/files/*) AND the short
# alias (/f/<id>) at the same time. Order matters: the more-specific
# /api/files prefix is registered first so a stray /f/api/files/...
# request (won't happen but principle of least surprise) hits the
# right handler.
combined_router = APIRouter()
combined_router.include_router(router)
combined_router.include_router(short_router)
combined_router.include_router(api_file_router)

# What the module manifest mounts. `router` keeps its original name
# for backward compat with any internal callers; `combined_router`
# is the canonical export.
router = combined_router  # noqa: F811 — intentional shadow
